acceptance_tests/features/load_seft_collection_instrument.feature, acceptance_tests/features/pages/collection_exercise_details.py, acceptance_tests/features/steps/load_seft_collection_instruments.py, resources/collection_instrument_files/wrong_ci_type.html
Added test scenarios for collection instrument file type validation
Works with [this PR](https://github.com/ONSdigital/response-operations-ui/pull/29) in response-operations-ui
[Trello](https://trello.com/c/jyN3I43Y/58-us027-validate-collection-instrument-file-format-size-medium)
[Confluence](https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/230490136/US027+Validate+Collection+Instrument+s+Medium)
=> Add tests for collection instrument validation

Makefile
If a developer isn't using python 3.6.0 or a python version with out
datetime module as their global python version the make file will use
that python version. It will cause the load scripts to fail.
Wrapping the command with pipenv will use the correct version of python
given pyenv is installed
=> Use pipenv for loading collection exercises and events

acceptance_tests/features/pages/collection_exercise.py, acceptance_tests/features/steps/view_collection_exercises_data.py, acceptance_tests/features/view_collection_exercises_data.feature
Added the integration tests for user story 11 displaying the state of a collection exercise
These tests wont pass currently if it is merged they are dependant on the backend stories passing data to respondent-ops ui
https://trello.com/c/kJO9QkLd
=> BDD us011 display state of a CE

acceptance_tests/features/pages/collection_exercise_details.py, acceptance_tests/features/steps/view_collection_exercise_created_state.py, acceptance_tests/features/steps/view_collection_exercise_details.py, acceptance_tests/features/view_collection_exercise_details.feature, acceptance_tests/features/view_collection_exercises_data.feature
Tests for the load variable event dates user story 
Please test this against the changes made to RM-tools and not using `make setup`
Run load.py and load_events.py aginst the changes made in rm-tools, then run `pipenv run python set_up_ce_execution.py` and `make acceptance tests` to test against the new data.
=> us018 load variable event dates

acceptance_tests/features/steps/view_collection_exercise_details_ready_for_review_state.py
Previously the tests were trying to get to a endpoints that looked like `/surveys/RSI/1811`
Now that we have updated data in rm tools the period should have 6 digits, i.e. `/surveys/RSI/201811`
=> Fix routing to RSI collection exercises

acceptance_tests/features/pages/reporting_unit.py, acceptance_tests/features/steps/view_reporting_unit_details.py, acceptance_tests/features/view_reporting_unit_details.feature
As an: internal user
I need: to be able to view respondent data for a Reporting Unit for a specific survey
So that: I understand the relationships with respondents for the Reporting Unit across surveys
Dependencies:
https://github.com/ONSdigital/ras-backstage/pull/53
https://github.com/ONSdigital/response-operations-ui/pull/55
=> tests for us046

Makefile
When running locally, we want to make sure that the services that are brought in by the Make start_services / test commands are using the latest versions.
=> Pull docker services before up

.travis.yml
[Makefile line](https://github.com/ONSdigital/rasrm-acceptance-tests/blob/master/Makefile#L42) it was duplicating.
=> Define test steps only in make file to avoid issues with duplication

acceptance_tests/features/pages/collection_exercise_details.py, acceptance_tests/features/select_eq_collection_instrument.feature, acceptance_tests/features/steps/select_eq_collection_instruments.py, controllers/collection_instrument_controller.py, set_up_ce_execution.py
Scenario: The user is able to select the EQ collection instruments to load into the collection exercise
Given the internal user navigates to the collection exercise details page for QBS 1803
When the user selects the collection instrument
Then the collection instrument is added into the collection exercise
Dependencies:
https://github.com/ONSdigital/ras-collection-instrument/pull/100
=> Add tests for adding eq ci

acceptance_tests/features/steps/view_reporting_unit_details.py
Changes introduced in https://github.com/ONSdigital/response-operations-ui/pull/74
adds extra text into the case group status field which will cause this
test to fail hence the `contains` check
=> Check for case group status in string

Makefile, acceptance_tests/features/pages/collection_exercise.py, acceptance_tests/features/steps/site_navigation.py, acceptance_tests/features/steps/view_collection_exercise_live_state.py, acceptance_tests/features/view_collection_exercise_live_state.feature, controllers/collection_exercise_controller.py
CE's with go-live events in the past in reality should have already been flagged somehow. This botches things somewhat by forcing the scheduler's hand with an alteration (via PUT to /events) to a collection exercise's go-live event.
To test: 
```bash
pipenv install --dev && make start_services system_tests setup && pipenv run behave acceptance_tests/features/view_collection_exercise_live_state.feature
```
=> US047 Add tests for viewing Live state of a collection exercise

acceptance_tests/features/edit_respondent_details.feature, acceptance_tests/features/environment.py, acceptance_tests/features/pages/edit_respondent_details_form.py, acceptance_tests/features/pages/reporting_unit.py, acceptance_tests/features/steps/edit_respondent_details.py, acceptance_tests/features/steps/view_reporting_unit_details.py, acceptance_tests/features/view_reporting_unit_details.feature, controllers/party_controller.py
Added tests for changing a respondent's email address.
[Confluence](https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/248545506/US058+Change+Respondents+Email+Address+XL)
[Trello](https://trello.com/c/KQUOeZBV/46-us058-int-change-respondent-email-address-xl)
Should be able to run from master branches.
=> US058 update respondent email

acceptance_tests/features/pages/reporting_unit.py, acceptance_tests/features/pages/surveys_todo.py, acceptance_tests/features/steps/view_collection_exercise_live_state.py, acceptance_tests/features/steps/view_reporting_unit_details.py, acceptance_tests/features/steps/view_survey_list.py, acceptance_tests/features/view_collection_exercise_live_state.feature, controllers/collection_exercise_controller.py
Changes in how we validate collection exercise event dates mean that the previous way we triggered/tested the live state transition of a collection exercise wont work.
We now create a new collection exercise which transitions into a live state over the course of the test
Works with changes in
[ras-frontstage](https://github.com/ONSdigital/ras-frontstage/pull/330)
=> Fix wait for live

Makefile
`make test` is skipping the acceptance tests at the moment.
This change fixes it so the acceptance tests. I am unsure why this fixes
it but it does.
Run `make test` and it should run all acceptance tests
=> Fixing `make test`

acceptance_tests/features/pages/reporting_unit.py, acceptance_tests/features/steps/edit_respondent_details.py, acceptance_tests/features/steps/enrolment_status_disable.py, acceptance_tests/features/steps/view_reporting_unit_details.py
When gathering collection exercises/respondents we now specify which survey we want them in the context of
This should fix the broken `view_reporting_unit_details` tests
=> Fix view reporting unit tests

README.md
To debug tests against the CF space we need to set a bunch of
environment variables in a shell and in pycharm. This change has a one
liner to be able to get all of those variables.
Follow steps in "Debugging tests against services deployed in Cloudfoundry" and  "To run in pycharm you'll need to put the same environment variables in" and check it works
=> Update README.md with easier instructions

Makefile, acceptance_tests/features/create_message_internal.feature, acceptance_tests/features/external_conversation.feature, acceptance_tests/features/inbox_internal.feature, acceptance_tests/features/reply_to_message_internal.feature, acceptance_tests/features/send_message_from_todo_list.feature, acceptance_tests/features/view_and_reply_conversation_external.feature, acceptance_tests/features/view_full_thread_internal.feature
Tagged all secure-message acceptance tests and added new targets to the Makefile to run either just the secure messaging acceptance tests or just the rasrm tests in isolation.
To test:
- Locally, run `make start_services wait_for_services setup acceptance_tests` to start all services and run the full test suite.  Ensure all tests run as expected.
- `make setup rasrm_acceptance_tests` should run only the rasrm acceptance tests (any tests that don't have a '@secure-messaging' tag).
- `make setup secure_messaging_acceptance_tests` should run only tests tagged with '@secure-messaging'
=> Secure messaging

README.md
Replace the single and double quotes to allow the command to be copied and pasted when users are setting up the DATABASE_NAME env var.  This is in line with the other commands in the Cloudfoundry setup steps.
=> Update command in README to allow for copying and pasting

README.md
To debug the tests against cloudfoundry you'll need to set some environment variables which can be tedious. This change is for a win liner to be able to extract that information from the pipeline
This needs changing due to the acceptance tests being split out
into two blocks, secure messaging and the rest.
=> Update get-pipeline grep

resources/database/database_reset_rm.sql
Currently actionplans aren't deleted when we run `database_reset_rm.sql`
With the changes coming to create actionplans at collection exercise creation we'll want these to be cleared as well
Added line to clear action plan table
Removed unnecessary insertion of action rule 
Ran the acceptance tests
Related to [PR in collection-exercise-service](https://github.com/ONSdigital/rm-collection-exercise-service/pull/65)
=> Delete action plans in database reset script

Makefile
Stop tests on first failure so time isn't wasted waiting to find out a
failed build. Also makes it easier to investigate failed builds because
the logs will be closed to the point in time when the failure occurred.
Add stop flag to stop tests on first failure
1. Put `raise Exception` here https://github.com/ONSdigital/rasrm-acceptance-tests/blob/master/acceptance_tests/features/steps/access_eq_collection_exercise.py#L12
2. Run `make test`
3. Observe tests stop immediately after failure
http://behave.readthedocs.io/en/latest/behave.html#cmdoption-stop
=> Stop tests on first failure

acceptance_tests/features/steps/external_conversation.py, resources/database/database_reset_secure_message.sql
Fixes the failing secure message test
Now clears down the secure messaging database tables before running the test that checks for no messages.
Run the secure message acceptance tests
=> Fix external user no messages test

Makefile, acceptance_tests/features/environment.py, acceptance_tests/features/steps/display_trading_as_external.py, controllers/case_controller.py, controllers/iac_controller.py, controllers/party_controller.py, resources/database/database_reset_rm.sql
New enrolment codes are now going to be generated with case events rather than the existing endpoint. The acceptance tests had to be updated to work with these changes.
When retrieving an existing enrolment code we now use casegroups/cases rather than database calls. If the existing code is inactive generate a new one against the found case
Run tests with associated PR's below
[Trello](https://trello.com/c/npXH3s9x/16-retain-current-enrolment-code-functionality-enrolment-codes)
Merge this last after the following below are in:
[case-service](https://github.com/ONSdigital/rm-case-service/pull/51)
[casesvc-api](https://github.com/ONSdigital/rm-casesvc-api/pull/21)
[response-operations-ui](https://github.com/ONSdigital/response-operations-ui/pull/201)
=> Remove bi/use case events for generating new enrolment codes

system_tests/features/steps/get_info_endpoints.py
Build is failing on master due to #148 incorrectly redefining a system test method.*
Name the new respondent home test correctly.
(* a missed typo)
=> Fix redefinition of r-ops system tests

acceptance_tests/features/pages/collection_exercise_details.py, acceptance_tests/features/steps/view_collection_exercise_live_state.py
Step `the user has confirmed that "{survey}" "{period}" is Ready for Live` failed where the collection exercise wasn't yet in `Ready for live`
Load sample failed where the load-sample-btn didn't exist.
* Add wait for element to be visible for load sample button as it is
rendered by javascript and may not be visible on page load
* Add check for text with retry for Ready for Live as this is an async
process. The collection exercise might not be in that state at the
time of running that step
Run the acceptance tests
=> Add test stability with wait and retries

resources/database/database_reset_rm.sql
The acceptance test will fail if the tests are ran twice because of a fk violation. This change deletes those records.
Delete records that have fk violation
Run the acceptance tests twice in a row
https://trello.com/c/wdlb13a3/193-create-acceptance-tests-for-enrolment-journey-5
=> Classifiertypeselector fk violation

acceptance_tests/__init__.py
One the 522 build on the ci-rasrm-acceptance-tests job in the rasrm
pipeline the tests failed because of a connection reset by peer. Don't
think we can do anything at that point other than retry.
Retry for connection reset by peer
1. Add `raise ProtocolError` to line 21 and check it retries on the error
https://$concourse/teams/rmras/pipelines/rasrm/jobs/ci-rasrm-acceptance-tests/builds/522
=> Retry on connection reset

README.md
The are some useful commands to get environment variables needed for
debugging the acceptance tests. The script was getting the environment
variables for the setup of the acceptance test rather than the
environment variables for running the tests meaning the SFTP details
weren't included in the output.
* This change makes all environment variables come back for debugging
tests
* Also simplifies the command
Follow debug steps to debug tests in CI
=> Simplify and fix command to get env variables

acceptance_tests/features/steps/notification_letter.py, controllers/collection_exercise_controller.py
Currently action rules are created manually by hitting action rules
API. The action rules will be created automatically when collection
exercise events are created. This reomves the need to hit the action
rules endpoint.
Remove manual action rules creation.
Run acceptance test
https://github.com/ONSdigital/rm-collection-exercise-service/pull/96
https://trello.com/c/Eknzy8H2/119-tbl123-link-action-rules-to-action-plans-at-create-time-create
=> Remove manual creation of action rules

acceptance_tests/features/pages/add_survey.py, acceptance_tests/features/pages/forgotten_password_respondent.py, acceptance_tests/features/pages/sign_in_respondent.py, acceptance_tests/features/pages/view_and_reply_conversation_external.py, acceptance_tests/features/steps/add_a_survey.py, acceptance_tests/features/steps/authentication.py, acceptance_tests/features/steps/survey_enrolment.py
Make frontstage button id naming consistent.
changed button ids in rasrm-acceptance-tests & ras-frontstage repos
test with ras-frontstage "inconsistant_html_button_id_naming" branch running locally in PyCharm etc... or from local docker image i.e docker build -t frontstage-ade .
all acceptance tests should pass.
https://github.com/ONSdigital/ras-frontstage/pull/381
=> 1st stage of button id naming

Makefile
The changes [here](https://github.com/ONSdigital/rasrm-acceptance-tests/pull/163/files#diff-b67911656ef5d18c4ae36cb6741b7965L43) prevents the pipeline from running acceptance tests as usual. 
Makefile
`make rasrm_acceptance_tests`
Pipeline should also go green after this is merged again(!)
=> Undo makefile changes

resources/database/database_reset_rm.sql
Survey ref is now allowed to be alphanumeric but one of the setup scripts in the acceptance tests casts it to an `int` for teardown, causing an error if you have any non numeric surveys in your database.
* Added regex check to the SQL script so it does not attempt to cast surveyref to integer if it contains any non numeric characters. Surveys with alphanumeric characters will be ignored by the teardown, preserving the current behaviour of removing any survey with numeric reference greater than 999.
Create a survey with non numeric characters in the survey ref. Run the acceptance tests, the setup up should run normally and not tear down the survey you created outside the tests.
https://github.com/ONSdigital/rm-survey-service/pull/55
=> Only attempt to cast/remove numeric survey refs in setup script

resources/database/database_reset_rm.sql
We no longer use the report table or sequence so removing reference to
them. This was removed in
https://github.com/ONSdigital/rm-actionexporter-service/pull/52
Remove reference to table and sequence
Using https://github.com/ONSdigital/rm-actionexporter-service/pull/52 run all the services then `make wait_for_services setup acceptance_tests`
=> Remove reset of removed tables

acceptance_tests/features/pages/create_message_external.py, acceptance_tests/features/send_message_from_todo_list.feature, acceptance_tests/features/steps/send_message_from_todo_list.py
On frontstage, The WAF gets triggered when a respondent types in more than 10,000 characters when creating a message. This PR is associated with the a branch on Frontstage- [Frontstage PR](https://github.com/ONSdigital/ras-frontstage/pull/394)
- Changed steps for creating a message so it goes up to 10,000 characters and not over
- Run acceptance tests with respective PR and all tests should pass
[Trello card](https://trello.com/c/1Oga8Jnv/317-frontstage-secure-message-rejected-by-waf-if-the-body-is-too-long)
=> Updating tests to work with creating secure-messages on frontstage

acceptance_tests/features/steps/view_collection_exercise_details.py
Currently time shows up with hard coded 'GMT' at the end. This has
been removed in response operations and now shows localised time.
Acceptance tests have been updated to accomodate this change.
Ran with branch -> https://github.com/ONSdigital/response-operations-ui/pull/235
=> Remove 'GMT' and use localised time

acceptance_tests/features/steps/view_collection_exercise_live_state.py
The test `a new exercise with period "X" is created and executed for BRICKS` in `view_collection_exercise_live_state.py` was setting a go_live date of 1 minute from the present time, which was not enough time for the sample units to be delivered, processed and the state to transition to `READY_FOR_LIVE` so the state transition was failing when the event message was processed.
Increased the amount of time to 2 minutes.
It's intermittent so it's hard to reproduce. Run the ATs and make sure they're still working.
Trello: https://trello.com/c/4Sx9t8R4/389-bug-fix-acceptance-test-intermittent-hanging
=> Fix intermittently failing test

acceptance_tests/features/steps/notification_letter.py
We are regularly seeing the acceptance test `the reporting unit will receive a letter` fail because of SFTP connection problems connecting to our FTP host. The logs say that it's a connection timeout on authentication so it seems reasonable that we should increase the amount of time before we get a timeout, given that I can connect without a problem to the SFTP host.
Increased connection timeout to 2 minutes.
Intermittent, so hard to reproduce. Run the ATs and make sure there's no regression.
Trello: https://trello.com/c/EzTfnHBO/400-bug-sftp-connection-timeout-in-acceptance-tests-checking-for-notify-letter
=> Increase timeout for SFTP connection to stop notify AT intermittent fail

acceptance_tests/features/steps/notification_letter.py, wait_until_services_up.py
When investigating a failed acceptance test, it was found that 2 files were created on the SFTP server in quick succession. There is insufficient logging to know which file the acceptance test is opening, and what IAC code it's looking for inside the file. This PR adds extra logging to the test so we can diagnose whether we need to fix the test or the Action Exporter service.
Added extra logging to `the reporting unit will receive a letter` scenario.
Run the acceptance tests and check that we're getting the extra log output.
Trello: https://trello.com/c/MLoPHcVk/402-bug-check-for-iac-code-in-sftp-file-intermittently-causes-ats-to-fail
=> Add log line to help diagnose bug

acceptance_tests/features/steps/change_response_status.py, common/enrolment_helper.py, common/social_survey_setup.py
The Collection Exercise service will automatically change the state of a collex on the `go_live` date provided that the state transition is valid, but if it's in `EXECUTION_STARTED` because it's still receiving sample units then the state transition will never happen because there's an error and no retry.
We could change the Collection Exercise service, but when would we ever set a `go_live` date one minute in the future and then attempt to upload a sample? Retries & DLQ in Collection Exercise are desirable, but beyond the scope of fixing these flakey acceptance tests.
Updated all the tests which set a `go_live` date 1 minute in the future to 2 minutes.
It's an intermittent fault which is hard to reproduce locally. Try running some really CPU & memory intensive stuff at the same time as …
=> Fix auto go_live dates set only 1 min in future = flakey acceptance tests

acceptance_tests/features/steps/change_response_status.py
We had an AT failing, when it was trying to navigate to the `history tab` once a survey had been set to `completed by phone`. What was hapening was when going to the history tab, the survey hadn't had enough time to appear. 
Just adding a wait between signing in and checkout out history page
Run AT's
=> Added wait between signng in and viewing history tab

acceptance_tests/features/steps/notification_letter.py
We are seeing the ATs fail intermittently complaining that an IAC code can't be found in a file. On investigation, the IAC code **IS** in the file, but the acceptance test is opening the file too quickly after it's seen it, and it's still in the process of being written to.
Added a 5 second completely arbitrary delay to the code which is looking for new files on the SFTP server, to give Action Exporter a bit more time to finish writing to the file.
Run the acceptance tests multiple times. It's an intermittent failure, so it's hard to know if it's resolved the issue or not.
Trello: https://trello.com/c/tGhKAtKm/445-bug-acceptance-tests-reading-sftp-files-while-they-are-still-being-written
=> Add delay to wait for file to finish being written to SFTP server

Makefile, acceptance_tests/features/steps/notification_letter.py, controllers/database_controller.py, reset_sftp_server.py
Currently only on enrolment code was getting checked, now we check
all of the expected enrolment code. 
Also the enrolment codes sometimes get written over multiple notification files, now we make sure we check all files instead of just one.
Now checking all enrolment codes are in the notification file.
Also check all notification files for that survey ref and 
collection exercise instead of just one.
Ran ATs
=> Make notification file test more robust

acceptance_tests/features/steps/social_disable_response_status.py, acceptance_tests/features/steps/social_survey_setup.py, common/social_survey_setup.py, controllers/case_controller.py
We are removing the `/casegroups/transitions/...` endpoint so casegroups now need to be transitioned with a case event
Replace calls to the casegroups transitions endpoints with case event posts
Acceptance tests should pass when ran with associated PR's
[Trello](https://trello.com/c/xkWvMZFk/420-use-case-event-rather-than-case-group-transition-for-change-response-status)
[response-operations-ui](https://github.com/ONSdigital/response-operations-ui/pull/250)
[response-operations-social-ui](https://github.com/ONSdigital/response-operations-social-ui/pull/17)
[rm-case-service](https://github.com/ONSdigital/rm-case-service/pull/93)
=> Use post case event endpoint instead of casegroup transition

acceptance_tests/features/steps/view_response_status.py, acceptance_tests/features/view_response_status.feature
New functionality added in to ROps RU page to view a response status when it is in a completed state. These AT's have come off the user story.
New feature for viewing response status
Run AT's against the branch in ROps, and review code standard.
[Trello Card](https://trello.com/c/mr2EipGk/287-us208-int-display-date-and-time-stamp-alongside-rus-ce-response-status-m)
[ROps PR](https://github.com/ONSdigital/response-operations-ui/pull/257)
=> Added acceptance tests for view response status feature

acceptance_tests/features/pages/respondent_unlocking_account.py
Made a change in frontstage to fix a grammar error in a string, this caused it to fail the get_lockout_message unit test as it checked for the exact string on the page.
Made the same change to the string in the unit test
run acceptance tests
https://trello.com/c/Lq59qtOH/556-fix-grammar-mistake-in-acceptance-tests
https://github.com/ONSdigital/rasrm-acceptance-tests/blob/d65ffa5fc6fa8af90f52ab3c7dd9f0c7fbb246ab/acceptance_tests/features/pages/respondent_unlocking_account.py#L35
=> Added 'a' to get_lockout_message to reflect ui changes

acceptance_tests/features/steps/unselect_collection_instruments.py
The CI pipeline is broken. It's broken because we are using specific collection exercises, which have specific go-live dates. The `Bricks` survey collection exercise `201811` went live at midnight tonight, which means that the Collection Exercise service will _automatically_ set this collection exercise to be live.
Changed the collection exercise used from November to December. This is a temporary fix to get the pipeline green.
Run the acceptance tests. Check the tests pass.
Trello: https://trello.com/c/DOsrckW2/585-bug-fix-the-ci-pipeline-failure-due-to-collection-exercise-go-live-date
=> Change collection exercise automatically live

acceptance_tests/features/steps/unselect_collection_instruments.py
Using Bricks' December 2018 collection exercise didn't work, because another test was using it (which will probably break in a month) so I needed to add a whole load of new collection exercises for 2019, so that I could use one of those.
These are stop-gap fixes to buy us more time, while we refactor the tests so that they don't use static dates and rely upon particular dates, which end up in the past and cause everything to break.
Used a new collection exercise (Bricks November 2019) created by rm-tools PR.
Run the acceptance tests.
Trello: https://trello.com/c/DOsrckW2/585-bug-fix-the-ci-pipeline-failure-due-to-collection-exercise-go-live-date
Related PR: https://github.com/ONSdigital/rm-tools/pull/30
=> Use new collection exercise from next year

acceptance_tests/features/edit_collection_exercise_details.feature, acceptance_tests/features/steps/edit_collection_exercise_details.py
Acceptance tests failing in CI due to element not available on page, because reload has not completed.
Added a sleep, to allow for the page to load before looking for an element.
Run the acceptance tests.
Trello: https://trello.com/c/DOsrckW2/585-bug-fix-the-ci-pipeline-failure-due-to-collection-exercise-go-live-date
=> Add sleep for aritrary time wait for page load

run_in_parallel.py
Currently the `run_in_parallel.py` script uses processes to parallelise execution. This PR changes this to use a standard library thread execution pool. It also defaults to gracefully stopping on the first failure, with the option to turn this off. This will cancel all not started scenarios and allow any in progress to complete before exiting.
- Use thread execution pool for parallel test execution
- Stop parallel tests on first failure by default
- Add command line option to not stop on first failure
- Small refactor of parallel _run_scenario function
Run the tests locally, all the parallel tests should still pass and the execution time should not be worse than before the changes.
Introduce a forced test failure and check the tests stop (note they will finish executing any other tests in …
=> Use thread pool for parallel execution, stop gracefully on test failure

controllers/database_controller.py
Our CI pipeline is hanging indefinitely because SQL is being executed, which never completes. We should abort after a reasonable timeout, so that the pipeline goes wrong and we fix the problem.
Added log line. Added timeout of 2 minutes for a single SQL script to run, which should be plenty for the reset databases scripts.
Run the acceptance tests. When this runs in the pipeline, we should see build failures instead of hung builds.
Trello: https://trello.com/c/1kikLuEl/594-bug-force-ci-pipeline-to-abort-sql-db-cleardown-scripts-that-hang
=> Force hung statements to abort

acceptance_tests/features/create_survey.feature, acceptance_tests/features/edit_survey_details.feature, acceptance_tests/features/environment.py, acceptance_tests/features/fixtures.py, acceptance_tests/features/steps/create_survey.py, acceptance_tests/features/steps/edit_survey_details.py, common/string_utilities.py, common/survey_utilities.py, run_in_parallel.py, run_in_sequence.py
To spread the knowledge about parallel tests , modify survey chosen because of its relative independence
Modified test to use data created during fixture execution. Minor import clean up, minor code tweaks in is_valid_parallel_environment and is_valid_sequential_environment. 
Modified Create survey to be parallelizable. Added support for matching to context object attributes in feature then strings. E.g "Then they get an error message of 'Survey with ID {survey_ref} already exists" in create_survey.
REDUCED RANDOMNESS of survey reference from 6 integers to 5 since a 9 was mandated as first and 7 characters fails validation
Make sure acceptance tests pass, view with local ui to validate survey created during test 
https://trello.com/c/kxHiqt1C
=> Edit survey details

Makefile, acceptance_tests/features/create_message_internal.feature, acceptance_tests/features/edit_respondent_details.feature, acceptance_tests/features/pages/create_message_internal.py, acceptance_tests/features/send_message_from_todo_list.feature, acceptance_tests/features/steps/create_message_internal.py, acceptance_tests/features/steps/send_message_from_todo_list.py, common/string_utilities.py
Remaining secure message tests converted to standalone
make setup acceptance_tests
and then
make secure_messaging_acceptance_tests
[Trello](https://trello.com/c/T0p0Gilm/386-t386convert-remaining-secure-messaging-features-to-standalone)
=> Remaining secure message tests converted to standalone

acceptance_tests/features/access_eq_collection_exercise.feature, acceptance_tests/features/environment.py, acceptance_tests/features/fixtures.py, acceptance_tests/features/steps/access_eq_collection_exercise.py, controllers/collection_exercise_controller.py, controllers/collection_instrument_controller.py
Converts the access eq collection exercise feature to standalone so it can be run in parallel
- Modified access eq collection exercise steps to use standalone setup data
- Added standalone and setup fixture tags to feature
- Added option to set up default CE data as EQ
- Small refactor of collection exercise setup to allow EQ instruments
Run `make acceptance_tests` locally. They should all pass and the access eq collection exercise feature should be skipped in the sequential run and included in the parallel.
https://trello.com/c/hqq9j2gf/389-t389-convert-access-eq-collection-exercise-feature-to-standalone
NB: This branches from refactor branch to avoid merge conflicts, this PR will point to master once that base branch is merged.
=> Standalone access eq collection exercise feature

acceptance_tests/features/account_unlocking_internal.feature, acceptance_tests/features/environment.py, acceptance_tests/features/fixtures.py, acceptance_tests/features/forgotten_password_respondent.feature, acceptance_tests/features/pages/forgotten_password_respondent.py, acceptance_tests/features/pages/respondent_unlocking_account.py, acceptance_tests/features/pages/respondent_verification.py, acceptance_tests/features/respondent_unlocking_account.feature, acceptance_tests/features/respondent_verification.feature, acceptance_tests/features/steps/account_unlocking_internal.py, acceptance_tests/features/steps/forgotten_password_respondent.py, acceptance_tests/features/steps/respondent_unlocking_account.py, acceptance_tests/features/steps/respondent_verification.py, common/generate_token.py, common/respondent_utilities.py
Converts the respondent account locking and unlocking related scenarios to standalone so they can be run in parallel. Also deletes 3 scenarios from the 'respondent_unlocks_account.feature' because they are duplicates from another feature file.
- Convert account unlocking internal feature to standalone
- Convert forgotten password respondent feature to standalone
- Convert respondent unlocking account feature to standalone
- Convert respondent verification feature to standalone
- Delete duplicate tests in respondent unlocking account
- Add function to generate a year old timestamped email reset JWT
Run `make acceptance_tests`
All tests should pass and the listed feature should now not run in the sequential batch and run in the parallel batch. …
=> Standalone account unlocking features

acceptance_tests/features/display_respondent_alongside_response_status.feature, acceptance_tests/features/pages/collection_exercise_details.py, acceptance_tests/features/send_message_from_todo_list.feature, acceptance_tests/features/steps/display_respondent_alongside_response_status.py
Feature tests for adding respondent name to the response status page in R-ops.
- Added feature file `display_respondent_alongside_response_status`
- Run with the [Response-ops PR](https://github.com/ONSdigital/response-operations-ui/pull/267) and run the acceptance tests. All should pass
[Trello](https://trello.com/c/1rcfmtok)
=> Feature tests for respondent on response status

acceptance_tests/features/display_respondent_alongside_response_status.feature
When the [display respondent](https://github.com/ONSdigital/rasrm-acceptance-tests/pull/222) PR got merged, the pipeline kept failing when doing one of the tests. This is because on CI and CI-latest we're unable to upload a collection instrument in frontstage which causes the test to fail. This PR adds a skip tag to the test so it can hopefully pass on the pipeline
- Added skip tag to test in display respondent
Run the acceptance tests and make sure that the test `Respondent field must be updated once an external user has completed a survey online` gets skipped while being run.
=> Skipped completed test for display respondent response status

acceptance_tests/features/steps/display_respondent_alongside_response_status.py
In the pipeline, a scenario is failing because an `ElementDoesNotExist` exception is raised. This PR fixes it so it ignores that exception and allows it to wait until the element is on screen.
Also changed the internal sign in to use context
- Added kwarg to `webdriverwait` so it will ignore the exception
- Internal sign in now uses context in `display_respondent_alongside_response_status`
- Run all acceptance tests to make sure they pass
=> Fixed webdriverwait to ignore Elementdoesnotexist

acceptance_tests/features/steps/view_survey_list.py
Blah blah blah tests using hard-coded dates etc.
Move dates a little bit into the future so that they break again on a predictable day.
Run the tests.
Trello: https://trello.com/c/Mv8D7thV/613-bug-fix-acceptance-tests-using-rsi-december-2018-collection-exercise-now-live
=> Fix test failing due to collex now live

acceptance_tests/features/remove_loaded_sample.feature, acceptance_tests/features/steps/remove-loaded-sample.py
Converts remove-loaded-sample to standalone. This feature is failing at the moment because of hardcoded dates being reached.
- Converted remove-loaded-sample.feature to standalone
Tests should all pass, remove-loaded-sample should be run in the parallel batch, not the sequential.
https://trello.com/c/ogTBNWPR/406-t406-acceptance-tests-convert-remove-loaded-samplefeature-to-standalone
=> Convert remove-loaded-sample feature to standalone

acceptance_tests/features/steps/inbox_internal.py, acceptance_tests/features/steps/view_and_reply_conversation_external.py, acceptance_tests/features/view_and_reply_conversation_external.feature
New functionality added in Fronstage to set the msg_to in secure message to a specific internal person when replying to a message from an internal person. So that the internal user can see the name of a person associated with the conversation
New test when a respondent replies to a message from the internal user checking that the msg_to has the expected internal user id
run the new scenario
Scenario: When a respondent replies to a message it is sent to the same internal user that sent the original message
https://trello.com/c/PGjxHXYA
=> Added test that respondent now replies to a specific internal user

acceptance_tests/features/reply_to_message_internal.feature, acceptance_tests/features/send_message_from_todo_list.feature, acceptance_tests/features/steps/reply_to_message_internal.py
When a Response-Ops UI user closes a secure message conversation, they should be returned to the inbox page they were on before they closed the conversation.
Added tests for improved functionality.
Run the scenarios `@sm599_s01` and `@sm599_s02` or the whole acceptance test suite, against the `response-operations-ui' branch of the same name.
Trello: https://trello.com/c/lCfPjUPT
=> Return user to page when closing conversation

run_in_parallel.py
Speed up tests a small bit
Removed a sleep(10) that existed due to lack of connections (fixed)
Checkout branch and run 
make acceptance_parallel_tests
https://trello.com/c/pzuQ5VK1/403-t403-acceptance-tests-speed-up
=> Remove sleep(10) between each scenario in parallel tests

acceptance_tests/features/steps/authentication.py, acceptance_tests/features/steps/view_and_reply_conversation_external.py, acceptance_tests/features/view_and_reply_conversation_external.feature
When a user clicks a link from an email, it would come up with an JWTValidation saying the user must sign in. What we want to happen is though, for the user to click the link and be directed to the sign in page. When they sign in they then get brought to the requested page they wanted. 
The test added just imitates what should happen when a user clicks a conversation link and isn't signed in.
- Added test to `view_and_reply_conversation_external.feature`
- Run acceptance test with [Frontstage PR](https://github.com/ONSdigital/ras-frontstage/pull/424)
[Trello](https://trello.com/c/nLsI8fjn)
=> Testing user redirected to login page when not signed in

acceptance_tests/features/fixtures.py, acceptance_tests/features/steps/add_a_survey.py, acceptance_tests/features/steps/inbox_internal.py, acceptance_tests/features/steps/reply_to_message_internal.py, acceptance_tests/features/steps/view_full_thread.py
Acceptance tests passing locally but not on build server . Assuming browser differences and race condition
Changed way to look for mark unread label missing , and allowed time for unread messages to be displayed
run tests
=> Tests passing locally not on build server , attempting to rectify

acceptance_tests/features/add_a_survey.feature
We need to revert a change on ras-frontstage and leaving this test in will break the pipeline. For the time being, we're gonna skip the test.
- Added skip tag to `User is trying to add a survey using a new iac code that they have previously added`
- Run the acceptance tests with [the revert branch](https://github.com/ONSdigital/ras-frontstage/tree/revert-already-added-survey) and make sure all tests pass
=> Skipping already added survey test

acceptance_tests/features/add_a_survey.feature, acceptance_tests/features/steps/inbox_internal.py, acceptance_tests/features/steps/reply_to_message_internal.py, acceptance_tests/features/view_full_thread_internal.feature, common/browser_utilities.py
Tests passing locally are failing in CI. With no indication why. We suspect that there may be timing issues. This will add an assert to each wait such that if after the wait period the element is still not present then an assert will be raised and visible in the output
Added assert to waits
Added wait for by class as the test that was using it passed locally and failed in CI , and used to use a by_class method
Run tests
=> 723 add asserts to wait

Pipfile, Pipfile.lock, acceptance_tests/__init__.py, acceptance_tests/features/pages/sign_in_internal.py
The PyPi package https://pypi.org/project/chromedriver_installer hasn't been maintained for 2 years, and the single contributor has failed to approve a pull request, which would fix a bug, due to the code screen-scraping a webpage to find the latest version of the ChromeDriver, which Google has changed.
Replace `chromedriver_installer` with `chromedriver-binary`. Add import to the init script so that the path is correctly set up for Selenium.
Run the acceptance tests. You should notice no difference.
Trello: https://trello.com/c/wyNCj7iF/738-bug-fix-the-ci-cd-pipeline-and-acceptance-tests
Old package fix pull request (unapproved): https://github.com/authomatic/chromedriver_installer/pull/10
New package: https://pypi.org/project/chromedriver-binary/
=> Change ChromeDriver package from buggy one to better maintained one

.travis.yml, acceptance_tests/__init__.py, acceptance_tests/features/add_a_survey.feature, acceptance_tests/features/environment.py, acceptance_tests/features/fixtures.py, acceptance_tests/features/pages/sign_in_internal.py, acceptance_tests/features/sign_in_internal.feature, acceptance_tests/features/steps/add_a_survey.py, acceptance_tests/features/steps/display_trading_as_external.py, acceptance_tests/features/steps/sign_in_internal.py, acceptance_tests/features/steps/social_sign_in_internal.py
Several acceptance tests did not have any actions in then clauses that could give rise to an exception. After adding asserts to these , some where failing. Most where fixed but a few around sign in seem to be a wider issue. I.e Flask validation messages not displaying as they are caught by html 'required' attribute which led to expected messages never being rendered
Added asserts and fixed failing tests
Run each test modified in a debugger. Place breakpoint at then clause and validate that assert is valid at that point
https://trello.com/c/PA09DqMB
=> 732 fix impotent then clauses

acceptance_tests/features/steps/view_collection_instrument.py, controllers/collection_instrument_controller.py
In the development environment, if you downloaded the example seft survey, then tried to reupload it, you'd have to change the file extension before you could (as xlxs isn't a valid extension)
The name of the example seft survey has been updated to have the correct extension when it's being set up.  There was also one place where it was looking for this, so we've updated it to look for the new (correct) full file name
=> Fix example seft survey file extension in development

Pipfile, Pipfile.lock, acceptance_tests/features/fixtures.py, common/collection_exercise_utilities.py, controllers/collection_exercise_controller.py
The tests for checking the collection exercise event dates puts the return_by and exercise_end date 10 days in the future which then gets changed to the BST time. This change should fix it so it saves it as UTC for the database and display the current timezone on the page.
- Tests should work with timezone differences of UTC and BST.
- Run the acceptance tests
- Run `view_collection_exercise_details.feature` with the date in april and the test should still pass.
=> Fixing tests for clocks going forward

acceptance_tests/features/re_send_verification.feature, acceptance_tests/features/steps/set_ready_for_live.py, common/collection_exercise_utilities.py
The pipeline has been broken for a couple of weeks and when testing it in the pipeline, there's some tests failing because of recent changes gone into response-operations-ui. These changes should hopefully get the pipeline green again.
- Changed test to find new alert message.
- Use local timezone for collection exercise events replace .
- Changed `re_send_verification.feature` to be a standalone test because it creates its own data.
- Run the acceptance tests and all should pass
=> Fixes for broken acceptance tests

acceptance_tests/features/steps/survey_enrolment.py
Test on the acceptance tests is failing due to a recent change that went into frontstage, this pr adds in the confirm email address box to the test so it can add the email address to it.
- Now checks for email_address_confirm
- Run the test locally and it should pass
=> Fixed survey enrolment test

README.md, run_in_parallel.py
Theres a bug when running the acceptance tests where it gets stuck when running the reset databases script. This will normally terminate after a few minutes but you waste so much time just waiting for the command to timeout. This PR shows you how to terminate the deadlocked process so you can save a bit of time while running the acceptance tests.
- Added section in the README about the reset database bug
- When running the acceptance tests, you could run the sql command to make sure it works as expected.
=> Adding reset databases fix to readme

acceptance_tests/features/steps/edit_collection_exercise_details.py
Removed a test for a feature that isn't there anymore
Edit collection exercise no longer checks for ability to edit user description, as this box has been removed.
Have commented the code out as it will need reintroducing when bug is properly addressed.
Run tests and ensure they don't fail on collection exercise editing. There are other fails happen intermittently, that are unrelated.
=> Removed test that temporarily doesn't apply due to bug fix

Makefile, Pipfile, Pipfile.lock, acceptance_tests/__init__.py, acceptance_tests/features/access_eq_collection_exercise.feature, acceptance_tests/features/enrolment-status-disable-enable.feature, acceptance_tests/features/fixtures.py, acceptance_tests/features/pages/collection_exercise.py, acceptance_tests/features/pages/collection_exercise_details.py, acceptance_tests/features/pages/reporting_unit.py, acceptance_tests/features/pages/sign_in_internal.py, acceptance_tests/features/pages/sign_out_internal.py, acceptance_tests/features/pages/surveys_history.py, acceptance_tests/features/pages/surveys_todo.py, acceptance_tests/features/sign_out_internal.feature, acceptance_tests/features/steps/authentication.py, acceptance_tests/features/steps/change_response_status.py, acceptance_tests/features/steps/edit_collection_exercise_details.py, acceptance_tests/features/steps/enrolment_status_disable.py, acceptance_tests/features/steps/sign_out_internal.py, acceptance_tests/features/steps/unselect_collection_instruments.py, acceptance_tests/features/steps/view_collection_exercises_data.py, acceptance_tests/features/view_collection_exercises_data.feature, acceptance_tests/features/view_full_thread_internal.feature, common/browser_utilities.py, controllers/messages_controller.py
Acceptance tests were failing seemingly randomly. This was an investigation to try and find why.
What was found was : 
1) Chrome driver in headless drops the session after 30 seconds , firefox does not
2)Several tests had finger in the air sleep statements , several of these changed to await for new elements , url changes etc
3) The remaining common failure is a 409 from the survey service which should be fixed by an upcoming release of survey service and tests
This release uses an environment variable called WEBDRIVER . This defaults to chrome , but can (and should) be over ridden to firefox. The dev can switch between firefox and chrome as and when they wish. We can then loop back around after everyone is using firefox and set the default to firefox.
Note gecko writes to geckodriver.log …
=> 937 additional waits and checks

acceptance_tests/features/pages/collection_exercise_details.py, acceptance_tests/features/set_ready_for_live.feature, acceptance_tests/features/steps/authentication.py, acceptance_tests/features/steps/edit_collection_exercise_details.py, acceptance_tests/features/steps/set_ready_for_live.py, acceptance_tests/features/steps/view_collection_exercises_data.py, common/browser_utilities.py
The previous merge inadvertently back out recent changes and introduced a bug.
Tests failing in ci because expected url was different to actual due to port display. So added a url comparator that ignored scheme and location.
A test was failing because locally collection exercises were processed quickly and we missed an in progress status. Removed test
Run the acceptance tests . These do not fix the survey service errors , that comes in a later PR
=> 1070 merge fixup and ci url fix

Pipfile, Pipfile.lock, acceptance_tests/features/pages/internal_conversation_view.py
When the previous bug fixes got to ci they uncovered a change where count of type ElementList ( from web driver) was no longer supported. In fixing this with a clean build locally I encountered errors with psycopg2. 
Removed psycopg2 leaving only psycopg2-binary .(Note had to use pipenv clean locally )
Changed how thread counts are calculated to get around the dropping of support for adding types ElementList
Run pipenv clean to remove any packages not in pipfile. Run pipenv install and pipenv install --dev
then run pipenv clean again . And then pipenv graph . psycopg2 should be missing and psycopg2-binary should be at the latest version (2.8.3) . Then run the acceptance tests 
https://trello.com/c/SRkARPd7
=> Removed psycopg2, just use binary and how thread counts are calculated

acceptance_tests/features/steps/create_survey.py
missing f  in fstring meant that error message was useless
https://trello.com/c/FNsVhmQq
=> added missing f

Pipfile.lock, acceptance_tests/__init__.py, acceptance_tests/features/inbox_internal.feature, acceptance_tests/features/pages/inbox_internal.py, acceptance_tests/features/steps/external_conversation.py, acceptance_tests/features/steps/inbox_internal.py, acceptance_tests/features/steps/view_and_reply_conversation_external.py
new tab on response ops , that should only show new conversations  from respondents
New test added that checks the number of messages in the case of new messages from both respondent and internal
Run acceptance tests
=> new-respondent-conversations

acceptance_tests/features/pages/collection_exercise_details.py, acceptance_tests/features/pages/inbox_internal.py, acceptance_tests/features/pages/reply_to_message_internal.py, acceptance_tests/features/reply_to_message_internal.feature, acceptance_tests/features/steps/external_conversation.py, acceptance_tests/features/steps/inbox_internal.py, acceptance_tests/features/steps/reply_to_message_internal.py, acceptance_tests/features/steps/set_ready_for_live.py, acceptance_tests/features/view_full_thread_internal.feature, common/browser_utilities.py, common/collection_exercise_utilities.py
response ops was not tracking the tab of origin of a conversation and was thus returning to open when a different tab was more appropriate. Also it was returning to the wrong tab. Most of the work was tested within response ops , but one scenario using the link in the flash message could not be easily tested that way so a new acceptance test was created
Deleted acceptance tests that replicated tests added to the response_ops repo.
Changed the tab definition to be a multi value conversation tab variable instead of bools to reflect changes in response ops. Refactored some tab selections to use a single call and be more DRY.
Run acceptance tests 
https://trello.com/c/mego4FuA
https://github.com/ONSdigital/response-operations-ui/compare/secure-message-return-to-tab?expand=1
=> validating correct tab when back via flash message

Makefile, acceptance_tests/features/inbox_internal.feature, acceptance_tests/features/pages/sign_in_respondent.py, acceptance_tests/features/steps/inbox_internal.py, acceptance_tests/features/steps/respondent_unlocking_account.py
There was a need to filter conversations in response operations by both survey and ru at the same time . This led to several tests being added to the response operations ui , and the deletion of tests here. Also tests that where testing the same functinality in this area where deleted
Several tests deleted 
Validate that tests deleted make sense
=> removed redundant tests , and tests moved to the response ops repo

acceptance_tests/features/forgotten_password_respondent.feature, acceptance_tests/features/pages/respondent.py, acceptance_tests/features/pages/respondent_unlocking_account.py, acceptance_tests/features/respondent_unlocking_account.feature, acceptance_tests/features/steps/create_collection_exercise.py, acceptance_tests/features/steps/display_trading_as_external.py, acceptance_tests/features/steps/reply_to_message_internal.py, acceptance_tests/features/steps/respondent_verification.py, acceptance_tests/features/steps/unselect_collection_instruments.py, acceptance_tests/features/steps/view_and_reply_conversation_external.py, acceptance_tests/features/steps/view_reporting_unit_details.py, collex-loader/load_events.py, common/browser_utilities.py, common/survey_utilities.py
From ticket “Fix acceptance tests”, change was needed to fix bugs during acceptance testing to prevent continual failure of tests on unchanged code and data.
Replaced duplicate method name with missing click_cancel, fixed wrong ID in get_respondent_details, bumped the expiry date of the workaround by two years, commented out failing password reset scenarios for now.
The tests now correctly flag up a dozen genuine test failures in the applications, which I've documented separately.
Build containers locally, and run "make acceptance tests" with Firefox webdriver.
https://trello.com/c/9FIFx6cf/1631-fix-acceptance-tests
=> Acceptance test fixes

_infra/spinnaker/smoke-test-pipeline.json
Chaitali and Tom can't execute the smoke test from Spinnaker 
Added their usernames to the list of namespaces in the smoke test pipeline 
From Spinnaker acceptance-tests, execute smoke test and ensure both names are visible in the "namespace" dropdown
- https://trello.com/c/ipiAl3s3
=> Update namespace list in smoke test pipeline
