ONSdigital/rasrm-acceptance-tests

config.py
views/features/get_info_endpoints.feature
views/features/steps/get_info_endpoints.py

- Added basic check for ras-frontstage-api.
- Removed ras-api-gateway tests.

Basic ras-frontstage-api test

---

Jenkinsfile
Pipfile
Pipfile.lock
README.md
acceptance_tests/__init__.py
acceptance_tests/features/environment.py
acceptance_tests/features/pages/survey.py
acceptance_tests/features/steps/view_survey_data.py
acceptance_tests/features/view_survey_data.feature
behave.ini
run.py
system_tests/features/get_info_endpoints.feature

Added test for https://trello.com/c/4uPzDISJ/23-us001b-view-survey-data-8pts
To test
1. Checkout response-operations-ui
1. Hack `surveys.py` to look like the example below
1. Install and run response-operations-ui with `pipenv install && pipenv run python run.py`
1. Run tests with be `pipenv run behave`
```
@app.route('/', methods=['GET'])
def view_surveys():
survey_list = [
{
"id": "cb0711c3-0ac8-41d3-ae0e-567e5ea1ef87",
"shortName": "RSI",
"longName": "Monthly Business Survey - Retail Sales Index",
"surveyRef": "023",
"legal_basis": "Statistics of Trade Act 1947"
},
{
"id": "cb0711c3-0ac8-41d3-ae0e-567e5ea1ef88",
"shortName": "BRUS",
"longName": "Business Register and Umployment Survey",
"surveyRef": "222",
"legal_basis": "Statistics of Trade Act 1947"
}
]
return …
```

Add BDD test for viewing surveys

---

.gitignore
Makefile

Three make targets:
install - install dependencies
system_tests: run system tests
acceptance_tests: run acceptance tests

Added Makefile

---

Makefile
README.md

Add pyenv and pipenv as prerequisites for clarification

Add pyenv pipenv docs

---

Pipfile
Pipfile.lock
acceptance_tests/features/breadcrumb_navigation.feature
acceptance_tests/features/environment.py
acceptance_tests/features/load_sample.feature
acceptance_tests/features/load_seft_collection_instrument.feature
acceptance_tests/features/sign_in_internal.feature
acceptance_tests/features/site_navigation.feature
acceptance_tests/features/steps/common.py
acceptance_tests/features/steps/sign_in_internal.py
acceptance_tests/features/view_collection_exercise_details.feature
acceptance_tests/features/view_collection_exercises.feature
acceptance_tests/features/view_collection_instrument.feature
acceptance_tests/features/view_sample.feature
acceptance_tests/features/view_survey_data.feature

This is a quick fix for the sign in and sign out for us334. The tests will be cleaned up and any formatting etc will be dealt with in another PR.

Hot-fix Internal sign in and out

---

Makefile
set_up_ce_execution.py

Now doesn't fail entirely if tmp_rm_tools wasn't deleted during the last run
(because it was killed in the middle of execution).  Also changed logging lines to
print so that it appears when being used in the makefile.

Improve makefile

---

acceptance_tests/features/pages/collection_exercise.py
acceptance_tests/features/steps/view_collection_exercise_created_state.py
acceptance_tests/features/steps/view_collection_exercise_details_ready_for_review_state.py
acceptance_tests/features/steps/view_collection_exercise_scheduled_state.py

Simple change to validate CE states and output state when assertions fail.

Ignore case of CE state with helper

---

Makefile
README.md

Local changes -> bring up services -> check services -> load initial state -> run tests -> bring down services.
Currently: bring up services -> load initial state -> fall over if local style issue.

Re-order make test to check services before setup

---

config.py

Use default UAA user for internal sign in.

Change internal user name and password to work with uaa

---

.gitignore
acceptance_tests/features/access_eq_collection_exercise.feature
acceptance_tests/features/create_message_internal.feature
acceptance_tests/features/environment.py
acceptance_tests/features/pages/reporting_unit.py
acceptance_tests/features/pages/surveys_todo.py
acceptance_tests/features/steps/access_eq_collection_exercise.py
acceptance_tests/features/steps/view_reporting_unit_details.py
acceptance_tests/features/view_collection_exercises_data.feature
controllers/collection_instrument_controller.py
controllers/database_controller.py
resources/database/collection_exercise_setup/qbs_1809_setup.sql
set_up_ce_execution.py

These tests should run with no errors against master branches.

tests for US062 - access eq survey

---

acceptance_tests/features/create_message_internal.feature

Removing skip tags from now passing tests

removing skip tags from tests

---

acceptance_tests/features/steps/load_seft_collection_instruments.py

https://github.com/ONSdigital/response-operations-ui/pull/97 will break one test.
This is a fix for that.

Fix for text change in response op

---

acceptance_tests/features/edit_respondent_details.feature
acceptance_tests/features/inbox_internal.feature
acceptance_tests/features/pages/inbox_internal.py
acceptance_tests/features/steps/inbox_internal.py
acceptance_tests/features/view_reporting_unit_details.feature

Added the ability to view messages by filter
[This PR needs to be tested against this PR](https://github.com/ONSdigital/response-operations-ui/pull/92)

SM139 Filter messages by survey

---

acceptance_tests/features/environment.py
controllers/database_controller.py

A lot of the tests rely the first respondent to be enrolled to RU 499000001 but the IAC code is only picked by the exercise id. This code change makes sure that the first respondent is enrolled to RU 499000001.

Register user to specific ru

---

acceptance_tests/features/environment.py
acceptance_tests/features/pages/surveys_todo.py
acceptance_tests/features/steps/view_reporting_unit_details.py
controllers/party_controller.py

Changed `/surveys` to `/surveys/todo` in surveys_todo.py

Fix tests for surveys todo url

---

config.py

Removed special secure messaging database so acceptance test database url needs to change

Changed secure messaging db URI to be standard one

---

acceptance_tests/features/environment.py
acceptance_tests/features/pages/respondent.py
acceptance_tests/features/search_respondent_by_email.feature
acceptance_tests/features/steps/find_respondent_by_email.py
acceptance_tests/features/steps/view_reporting_unit_details.py
controllers/party_controller.py

Tests for search respondent by email. Also sets any respondents being created to active to allow them to login to frontstage.

US091 Internal search for respondent by email

---

Jenkinsfile

Updating the file to allow the tests to be run in the ci space.

updating file for new space and adding missing config

---

acceptance_tests/features/edit_collection_exercise_details.feature
acceptance_tests/features/pages/collection_exercise_details.py
acceptance_tests/features/pages/edit_collection_exercise_details_form.py
acceptance_tests/features/steps/edit_collection_exercise_details.py

Run against:
https://github.com/ONSdigital/response-operations-ui/pull/111
https://github.com/ONSdigital/ras-backstage/pull/88

US107 edit ce details

---

Makefile
setup_data.sh
start_services.sh
stop_services.sh

Pulling scripts for make targets start_services to ./start_services.sh,
stop_services to stop_services.sh, setup to setup_data.sh

Simplify make file by splitting out into scripts

---

resources/database/collection_exercise_setup/rsi_201812_setup.sql
resources/database/database_reset_rm.sql

Once https://github.com/ONSdigital/rm-action-service/pull/38 is merged in tests will fail becuase of a table change.
This PR fixes it.

FIX add uuid to action rule inserts

---

.travis.yml
acceptance_tests/features/pages/respondent.py
acceptance_tests/features/search_respondent_by_email.feature
acceptance_tests/features/steps/find_respondent_by_email.py

https://github.com/ONSdigital/ras-deploy/pull/4

Fix issues with new respondent details page

---

README.md

Changing the documentation to use the right app name.
Follow steps to check it works

Fix debugging doc

---

acceptance_tests/__init__.py

Not needed for tests to pass
Removing fixed window size
Run acceptance tests

Remove fixed window size for headless

---

acceptance_tests/features/environment.py
common/respondent_details.py
controllers/case_controller.py
controllers/database_controller.py

Remove unused code and address linting issues

Address linting issues

---

acceptance_tests/features/pages/forgotten_password_respondent.py
acceptance_tests/features/steps/respondent_verification.py

a small bug was merged in where, instead of looking for Frontstage was using localhost which failed in ci
use config.frontstag_service

use config for frontstage service

---

acceptance_tests/features/steps/respondent_verification.py

an assert was using an f string which wont work

fix assert doesnt use f string

---

acceptance_tests/features/steps/social_disable_response_status.py

Minor bug fix to login into Social app

Login into Social app fix

---

acceptance_tests/features/environment.py
acceptance_tests/features/pages/surveys_history.py
acceptance_tests/features/steps/change_response_status.py
acceptance_tests/features/steps/notification_letter.py
controllers/collection_exercise_controller.py
controllers/database_controller.py

Removed all arbitrary sleep time to polling mechanism.
Using polling mechanism
run acceptance tests
https://trello.com/c/iOnp7jzP/434-remove-arbitrary-wait-times-in-acceptance-tests-s#

remove arbitrary wait times in acceptance tests

---

run_in_sequence.py

Quick temporary fix for Concourse

Temporarily deleted system acceptance test execution

---

acceptance_tests/features/pages/create_message_internal.py

External conversation acceptance test fix

External conversation class fix

---

acceptance_tests/features/steps/social_sign_in_internal.py

Content changes in response-operations-social-ui require a string change in the acceptance tests.
* Update social home page title in assertion
Run against this branch of r-ops-social, all social tagged tests should pass https://github.com/ONSdigital/response-operations-social-ui/pull/19
https://trello.com/c/yCnRVGM8/326-update-sel-ui-to-use-the-pattern-library-cdn
https://github.com/ONSdigital/response-operations-social-ui/pull/19

Update social home page title

---

acceptance_tests/features/environment.py
acceptance_tests/features/fixtures.py
acceptance_tests/features/social_view_closed_case_details.feature
acceptance_tests/features/steps/social_view_case_details.py
common/survey_utilities.py

Acceptance test for [changes made in SEL UI](https://github.com/ONSdigital/response-operations-social-ui/pull/22).
NB: Builds on the implementation from https://github.com/ONSdigital/rasrm-acceptance-tests/pull/207.

SUS055 Hide status and IAC buttons and display message if CE closed

---

acceptance_tests/features/search_respondent_by_email.feature
acceptance_tests/features/steps/find_respondent_by_email.py

Converted search_respondent_by_email to standalone
[Trello Card](https://trello.com/c/goJdSB3o/346-t335-acceptance-tests-convert-searchrespondentbyemail-to-standalone)

Converted search_respondent_by_email to standalone

---

acceptance_tests/features/edit_respondent_details.feature
acceptance_tests/features/environment.py
acceptance_tests/features/fixtures.py
acceptance_tests/features/steps/edit_respondent_details.py
common/respondent_utilities.py
common/survey_utilities.py
controllers/database_controller.py

Converted edit_respondent_details.feature to standalone
#Link
[Trello](https://trello.com/c/XExcWx0d/334-acceptance-tests-convert-editrespondentdetails-to-standalone)

Standalone edit respondent details

---

controllers/database_controller.py

missing database_uri parameter fix

Added missing database_uri parameter

---

acceptance_tests/features/pages/survey.py
acceptance_tests/features/site_navigation.feature
acceptance_tests/features/steps/site_navigation.py

Fails Intermittently and holding up more important PRs
[Trello](https://trello.com/c/iNXXXl13/362-t339-acceptance-tests-rollback-sitenavigation-feature-to-sequential)

Rollback site_navigation.feature to run sequentially

---

common/internal_utilities.py
config.py

uaa deploy changes
https://github.com/ONSdigital/ras-deploy/pull/100

uaa deploy changes

---

acceptance_tests/features/external_conversation.feature
acceptance_tests/features/fixtures.py
acceptance_tests/features/inbox_internal.feature
acceptance_tests/features/pages/external_conversation.py
acceptance_tests/features/pages/inbox_internal.py
acceptance_tests/features/pages/reply_to_message_internal.py
acceptance_tests/features/reply_to_message_internal.feature
acceptance_tests/features/steps/external_conversation.py
acceptance_tests/features/steps/inbox_internal.py
acceptance_tests/features/steps/reply_to_message_internal.py
acceptance_tests/features/steps/view_and_reply_conversation_external.py
acceptance_tests/features/steps/view_full_thread.py
acceptance_tests/features/view_and_reply_conversation_external.feature
acceptance_tests/features/view_full_thread_internal.feature
common/internal_utilities.py
controllers/messages_controller.py

reply_to_message_internal, view_and_reply_conversation_external, external_conversation, view_full_thread_internal & inbox_internal done features converted to standalone
[Trello](https://trello.com/c/k9fDhw9w/354-t354-acceptance-tests-convert-multiple-to-standalone)

Standalone multiple acceptance tests

---

Makefile
acceptance_tests/features/environment.py
acceptance_tests/features/fixtures.py
acceptance_tests/features/steps/notification_letter.py
acceptance_tests/features/steps/set_ready_for_live.py
common/collection_exercise_utilities.py
common/common_utilities.py
common/respondent_utilities.py
common/survey_utilities.py
controllers/collection_instrument_controller.py
controllers/django_oauth_controller.py
controllers/party_controller.py
controllers/sample_controller.py
controllers/survey_controller.py
run_in_parallel.py
run_in_sequence.py
run_tags.py

to improve/reduce test log output
Sets a global logging level
Changed some log statement to debug level
[Trello](https://trello.com/c/v8QqqpMe/377-acceptance-tests-logging)

Improve acceptance logging

---

acceptance_tests/features/edit_collection_exercise_details.feature
acceptance_tests/features/environment.py
acceptance_tests/features/fixtures.py
acceptance_tests/features/load_sample.feature
acceptance_tests/features/load_seft_collection_instrument.feature
acceptance_tests/features/send_message_from_todo_list.feature
acceptance_tests/features/steps/load_sample.py
acceptance_tests/features/steps/load_seft_collection_instruments.py
acceptance_tests/features/steps/view_collection_exercise_created_state.py
acceptance_tests/features/steps/view_collection_exercise_details.py
acceptance_tests/features/steps/view_collection_exercise_details_ready_for_review_state.py
acceptance_tests/features/steps/view_collection_exercise_live_state.py
acceptance_tests/features/steps/view_collection_exercise_scheduled_state.py
acceptance_tests/features/steps/view_collection_instrument.py
acceptance_tests/features/view_collection_exercise_details.feature
acceptance_tests/features/view_collection_exercise_details_ready_for_review_state.feature
acceptance_tests/features/view_collection_exercise_details_state.feature
acceptance_tests/features/view_collection_exercise_live_state.feature
acceptance_tests/features/view_collection_exercise_scheduled_state.feature
acceptance_tests/features/view_collection_instrument.feature
common/collection_exercise_utilities.py
controllers/collection_exercise_controller.py
controllers/database_controller.py

converted to standalone - 
load_sample.feature
load_seft_collection_instrument.feature
send_message_from_todo_list.feature
view_collection_exercise_details.feature
view_collection_exercise_details_ready_for_review_state.feature
view_collection_exercise_details_state.feature
view_collection_exercise_live_state.feature
view_collection_exercise_scheduled_state.feature
view_collection_instrument.feature
[Trello](https://trello.com/c/pfByqsDu/387-t387convert-multiple-view-collection-exercise-features-to-standalone)

Multiple features to standalone

---

acceptance_tests/features/create_collection_exercise.feature
acceptance_tests/features/fixtures.py
acceptance_tests/features/pages/sign_out_internal.py
acceptance_tests/features/steps/create_collection_exercise.py
controllers/collection_exercise_controller.py

Converted create_collection_exercise.feature to standalone
[Trello](https://trello.com/c/IsMSUmDI/400-t400acceptance-testscreatecollectionexercise)

Create collection exercise

---

acceptance_tests/features/find_reporting_unit.feature
acceptance_tests/features/steps/find_reporting_unit.py

Converted find_reporting_unit.feature to standalone
[Trello](https://trello.com/c/fQLy2aE3/404-t404acceptance-testsfindreportingunitfeature)

Converted find_reporting_unit.feature to standalone

---

acceptance_tests/features/notification_letter.feature
acceptance_tests/features/set_ready_for_live.feature
acceptance_tests/features/steps/notification_letter.py

Converted notification_letter.feature to standalone
[Trello](https://trello.com/c/j38peObI/407-t407acceptance-testsnotificationletter)

Notification letter

---

acceptance_tests/features/steps/view_sample.py
acceptance_tests/features/view_sample.feature

Converted view_sample.feature to standalone
[Trello](https://trello.com/b/E9lArxTH/ras-rm-orange)

Converted view_sample.feature to standalone

---

acceptance_tests/features/steps/view_reporting_unit_details.py
acceptance_tests/features/view_reporting_unit_details.feature

Converted view_reporting_unit_details.feature to standalone
[Trello](https://trello.com/c/uxPXzqlN/417-t417acceptance-testsviewreportingunitdetails)

Converted view_reporting_unit_details.feature to standalone

---

acceptance_tests/features/pages/collection_exercise.py
acceptance_tests/features/pages/create_message_internal.py
acceptance_tests/features/pages/internal_conversation_view.py
acceptance_tests/features/pages/view_and_reply_conversation_external.py
acceptance_tests/features/reply_to_message_internal.feature
acceptance_tests/features/steps/edit_collection_exercise_details.py
acceptance_tests/features/steps/inbox_internal.py
acceptance_tests/features/steps/reply_to_message_internal.py
acceptance_tests/features/steps/view_collection_exercise_details_ready_for_review_state.py
acceptance_tests/features/steps/view_collection_exercises_data.py
acceptance_tests/features/steps/view_full_thread.py
acceptance_tests/features/view_full_thread_internal.feature
common/browser_utilities.py
controllers/messages_controller.py

Pressing mark unread was returning user to wrong page. Also some tests worked locally and not remotely 
Added extra tests . 
Run tests

Return to page when unread

---

acceptance_tests/features/environment.py
acceptance_tests/features/fixtures.py
acceptance_tests/features/re_send_verification.feature
acceptance_tests/features/respondent_verification.feature

the way the fixture was working caused the tests to be  unreliable
created a new fixture and moved new tests to new feature file
Run ATs 
https://trello.com/c/JOPM1IFq/394-us216-view-respondent-details-m

added new fixture and feature file

---

acceptance_tests/features/enrolment-status-disable-enable.feature
acceptance_tests/features/fixtures.py
acceptance_tests/features/pages/respondent.py
acceptance_tests/features/steps/find_respondent_by_email.py
common/collection_exercise_utilities.py
common/respondent_utilities.py

Addresses broken tests caused by recent resops changes
A number of tests were affected by how tests navigated to respondent pages, I've re-addressed how we navigate to respondent pages when not testing the journey to them.
Read code, comment.
Run acceptance tests to ensure they pass - I have some sporadic failures, but not just on this branch.
https://trello.com/c/Mi1Zpw1l

Search respondents ui

---

acceptance_tests/features/steps/find_respondent_by_email.py

Removes a function that was commented out but not removed previously.

Removed commented out function

---

acceptance_tests/features/steps/edit_collection_exercise_details.py

Missed a step from the last fix, now added.

Remove edit from user period ce

---

acceptance_tests/features/pages/collection_exercise_details.py
acceptance_tests/features/pages/social_sign_in_internal.py
acceptance_tests/features/social_sign_in_internal.feature
acceptance_tests/features/steps/social_sign_in_internal.py
controllers/collection_exercise_controller.py
controllers/survey_controller.py

acceptance test changes for survey service
changed tests to acomodate changes
run ATs
https://trello.com/c/GvoKYQUd/1077-merge-in-ryans-acceptance-test-changes-after-survey-service-changes-have-made-it-to-master

Fixes for new survey changes

---

acceptance_tests/features/add_a_survey.feature

There was an IAC test that was commented out until some work was done.  The work has been done so the test is now valid again.
Removed skip from a test
Run the tests, they should pass
https://trello.com/c/R7M5uhMM

Remove skipped iac test

---

acceptance_tests/features/create_survey.feature

tests failing due to change in error string 
https://trello.com/c/mvbOp70b

Change in error string

---

resources/database/database_reset_oauth.sql

tests failing on sql execution as table no longer exists
removed truncation of old table
https://trello.com/c/OLOF4SWs

remove truncation of table that no longer exists

---

README.md

Add instructions to switch to firefox.

---

acceptance_tests/features/pages/collection_exercise.py
acceptance_tests/features/steps/view_collection_exercise_live_state.py
common/browser_utilities.py

refactor collection exercise led to a few tests need changing 
Also improved logging and fixed a bug due to DST ( we are in 1st week after clocks change)
Run acceptance tests , use gecko driver for firefox and export WEBDRIVER=firefox reccomended
https://trello.com/c/4Midc4vj

Refactor collection exercise

---

acceptance_tests/features/pages/internal_conversation_view.py
acceptance_tests/features/steps/reply_to_message_internal.py

Updated how latest message is identified

---

acceptance_tests/features/pages/collection_exercise.py
acceptance_tests/features/pages/forgotten_password_respondent.py
run_feature.py

PR
From ticket “Fix acceptance tests”, change was needed to fix timeouts during acceptance testing to prevent continual failure of tests on unchanged code and data.
Added timeouts to Selenium tests.
No refactoring was required.
No new tests written, as this fix is on a set of tests. 
**For all tests**:
make test 
**For just create_collection_exercise**:
make setup
make TEST_TARGET=acceptance_tests/features/create_collection_exercise.feature run_tests
https://trello.com/c/9FIFx6cf/1631-fix-acceptance-tests

Explicit waits

---

_infra/helm/acceptance-tests/templates/job.yaml
_infra/helm/acceptance-tests/values.yaml

selectable version

---

_infra/spinnaker/smoke-test-pipeline.json

typo in dev namespace for Amit S

Namespace fix

---

Dockerfile

Firefox binary needed for testing with firefox webdriver

install firefox

---

_infra/docker/Dockerfile

update debian source for firefox install
